// Browser verification for the documentation prototype; no product test dependencies.
import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('.',import.meta.url));
const tabs=await (await fetch('http://127.0.0.1:9228/json')).json();
const ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);
await new Promise(r=>ws.addEventListener('open',r,{once:true}));
let seq=0;const waiting=new Map();const exceptions=[];
ws.addEventListener('message',({data})=>{const x=JSON.parse(data);if(x.method==='Runtime.exceptionThrown')exceptions.push(x.params.exceptionDetails);if(waiting.has(x.id)){const [res,rej]=waiting.get(x.id);waiting.delete(x.id);x.error?rej(x.error):res(x.result);}});
function cdp(method,params={}){return new Promise((res,rej)=>{const id=++seq;waiting.set(id,[res,rej]);ws.send(JSON.stringify({id,method,params}));});}
async function js(expression){const r=await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw new Error(JSON.stringify(r.exceptionDetails));return r.result.value;}
async function nav(screen){await cdp('Page.navigate',{url:'http://127.0.0.1:8042/screen.html?screen='+screen});for(let n=0;n<60;n++){await new Promise(r=>setTimeout(r,50));if(await js(`document.readyState==='complete' && document.title===${JSON.stringify('Sweet · '+screen.split('&')[0].replaceAll('-',' '))}`))return;}throw new Error('Navigation timeout: '+screen);}
async function shot(name){const {data}=await cdp('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});await fs.writeFile(root+'captures/'+name+'.png',Buffer.from(data,'base64'));}
await fs.mkdir(root+'captures',{recursive:true});await cdp('Runtime.enable');await cdp('Page.enable');await cdp('Emulation.setDeviceMetricsOverride',{width:402,height:874,deviceScaleFactor:1,mobile:false});
const screens=['home-a','home-b','home-c','home-left','face-ready','face-scan','face-adjust','face-result','face-detail','face-baseline-empty','face-all','skin-ready','skin-review','skin-result','skin-detail','skin-all','skin-error','gut-capture','gut-result','ask&context=gut','history','history-face','compare-select','compare','compare-limited','history-empty','saved-check&record=f06','health','settings-left','settings-right'];
const report={screens:[],interactions:[],exceptions};
for(const screen of screens){await nav(screen);await shot(screen.replaceAll('&context=','-').replaceAll('&record=','-'));report.screens.push(await js(`(()=>{const p=document.querySelector('#phone'),s=document.querySelector('.scroll');return {screen:${JSON.stringify(screen)},phone:[p.offsetWidth,p.offsetHeight],overflowX:p.scrollWidth>p.clientWidth,scrollHeight:s?.scrollHeight,viewport:s?.clientHeight,tabs:[...document.querySelectorAll('.tab')].map(e=>e.innerText),honestyLines:[...document.querySelectorAll('.quiet')].filter(e=>e.textContent.includes('diagnosis')).length,visibleVendorText:/shen|perfect corp|stoolanalyzer|poopcheck|SDNN/i.test(p.innerText),h1:document.querySelector('h1')?.innerText};})()`));}
async function check(name,expr){const passed=await js(expr);report.interactions.push({name,passed});if(!passed)throw new Error('Failed: '+name);}
await nav('home-a');await js(`document.querySelector('.check-row').click()`);await new Promise(r=>setTimeout(r,150));await check('Home Face row enters capture',`location.search.includes('face-ready')`);
await js(`document.querySelector('[data-play]').click()`);await new Promise(r=>setTimeout(r,180));await check('Start enters synthetic scan',`location.search.includes('face-scan')`);
await new Promise(r=>setTimeout(r,4700));await check('Synthetic scan completes into six hero tiles',`document.querySelectorAll('.hero-tile').length===6`);
await nav('face-ready');await js(`document.querySelector('.capture-x').click()`);await new Promise(r=>setTimeout(r,140));await check('X leaves camera',`location.search.includes('home-a')`);
await nav('skin-ready');await js(`document.querySelector('.shutter').click()`);await new Promise(r=>setTimeout(r,140));await check('Skin shutter opens still review',`location.search.includes('skin-review')`);
await js(`document.querySelector('.button-pair .secondary-button').click()`);await new Promise(r=>setTimeout(r,140));await check('Retake returns to Skin guide',`location.search.includes('skin-ready')`);
await nav('history');for(const f of ['Face','Skin','Gut','All']){await js(`document.querySelector('[data-filter="${f}"]').click()`);await check('History filter '+f,`[...document.querySelectorAll('.history-row h3')].every(e=>${JSON.stringify(f)}==='All'||e.innerText.startsWith(${JSON.stringify(f)}))`);}
await nav('history&filter=Face');await js(`document.querySelector('.history-row[href*="record=f06"]').click()`);await new Promise(r=>setTimeout(r,140));await check('Older History entry preserves its date and HRV',`document.querySelector('.eyebrow').textContent.includes('Sep 6')&&document.querySelector('.data-list').innerText.includes('39 ms')`);await js(`document.querySelector('.topbar a').click()`);await new Promise(r=>setTimeout(r,140));await check('Back preserves Face filter',`document.querySelector('.filter.active').textContent==='Face'`);
await nav('compare-select');await check('Compare starts disabled',`document.querySelector('#compare-go').disabled`);for(const id of ['f06','f13'])await js(`document.querySelector('[data-select="${id}"]').click()`);await check('Two selections enable comparison',`!document.querySelector('#compare-go').disabled&&document.querySelectorAll('.history-row.selected').length===2`);await js(`document.querySelector('[data-select="f10"]').click()`);await check('Third selection does not replace first two',`document.querySelectorAll('.history-row.selected').length===2&&!document.querySelector('[data-select="f10"]').classList.contains('selected')`);await js(`document.querySelector('#compare-go').click()`);await new Promise(r=>setTimeout(r,150));await check('Selected checks reach comparison',`document.querySelector('.compare-table').innerText.includes('39')&&document.querySelector('.compare-table').innerText.includes('42')`);
await nav('ask&context=gut');await js(`document.querySelector('#ask-prompt').click()`);await check('Ask follow-up responds',`document.querySelectorAll('.bubble.reply').length===2`);
await nav('history&filter=Face');await check('History retains all 21 baseline mornings plus one evening',`document.querySelectorAll('.history-row').length===22`);
await nav('compare&checks=m8d12,f13');await check('Arbitrary selected pair gets its actual interval and difference',`document.querySelector('h1').innerText.includes('A day apart')&&document.querySelector('.care-card').innerText.includes('1 ms higher')`);await js(`document.querySelector('.inline-link').click()`);await new Promise(r=>setTimeout(r,150));await js(`document.querySelector('.topbar a').click()`);await new Promise(r=>setTimeout(r,150));await check('Baseline Back returns to the chosen comparison',`location.search.includes('compare')&&document.querySelector('.compare-table').innerText.includes('Sep 12')`);
await nav('home-c');await js(`document.querySelector('.check-row').click()`);await new Promise(r=>setTimeout(r,150));await js(`document.querySelector('.capture-x').click()`);await new Promise(r=>setTimeout(r,150));await check('Capture X preserves chosen Home treatment',`location.search.includes('home-c')`);
await nav('face-adjust');await check('Reposition keeps a fixed clipping guide and has no manual resume',`!document.querySelector('.capture-button')&&getComputedStyle(document.querySelector('.camera-clear')).transform==='none'`);
await nav('face-scan');await check('Only one visible scan instruction; neutral working symbol',`document.querySelector('.capture-action').innerText===''&&document.querySelectorAll('.working circle').length===3&&!document.querySelector('.scan-arc')`);
await nav('settings-left');await js(`document.querySelector('#profile').requestSubmit()`);await check('Profile units and local preview save',`document.querySelector('#profile-note').textContent.includes('preview')&&document.querySelector('label').textContent.includes('in')`);
await nav('gut-result');await js(`document.querySelector('.scroll').scrollTop=99999`);await shot('gut-result-bottom');await check('Gut clinician section fully reachable above navigation',`(()=>{let c=document.querySelector('.clinician').getBoundingClientRect(),s=document.querySelector('.scroll').getBoundingClientRect();return c.top>=s.top&&c.bottom<=s.bottom;})()`);
await cdp('Emulation.setEmulatedMedia',{features:[{name:'prefers-reduced-motion',value:'reduce'}]});await nav('face-scan');await check('Reduce motion stops working glyph animation',`getComputedStyle(document.querySelector('.working svg')).animationName==='none'`);
report.checkedAtEastern=new Date().toLocaleString('en-US',{timeZone:'America/New_York',timeZoneName:'short'});
await fs.writeFile(root+'verification.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({screens:report.screens.length,interactions:report.interactions,exceptions:exceptions.length,overflow:report.screens.filter(s=>s.overflowX),vendorLeaks:report.screens.filter(s=>s.visibleVendorText)},null,2));ws.close();
